#!/bin/sh -ex

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

DB_NAME=wikidb
DB_USER=wikiuser

ETC_DIR=/etc/dekiwiki
WEB_DIR=/var/www/dekiwiki

# configure apache
rm /etc/apache2/sites-available/dekiwiki
ln -s $ETC_DIR/apache.conf /etc/apache2/sites-available/dekiwiki

a2ensite dekiwiki
a2dissite default

a2enmod rewrite
a2enmod proxy
a2enmod proxy_http

# start mysql and apache
/etc/init.d/mysql start
/etc/init.d/apache2 start

# complete the installation
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/config/install.php?params=start"

curl --data "SelectedEdition=core&Sitename=Mindtouch+Core&SysopEmail=$EMAIL&SiteLang=en-us&RegistrarFirstName=&RegistrarLastName=&RegistrarPhone=&SysopPass=$ADMIN_PASS&SysopPass2=$ADMIN_PASS&DBserver=localhost&DBname=$DB_NAME&DBuser=$DB_USER&RootUser=root&RootPW=&Mono=%2Fusr%2Fbin%2Fmono&ImageMagickConvert=%2Fusr%2Fbin%2Fconvert&ImageMagickIdentify=%2Fusr%2Fbin%2Fidentify&prince=%2Fusr%2Fbin%2Fprince&RegistrarCount=0&RegistrarDept=" $URL

CONFIG=$WEB_DIR/config
mkdir -p $ETC_DIR
mv $CONFIG/mindtouch.host.conf $ETC_DIR
mv $CONFIG/mindtouch.deki.startup.xml $ETC_DIR
mv $CONFIG/LocalSettings.php $WEB_DIR
ln -s $WEB_DIR/LocalSettings.php $ETC_DIR/LocalSettings.php

# create welcome page
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE $DB_NAME;
UPDATE pages SET
page_display_name = 'TurnKey Mindtouch Core (Deki)',
page_tip = 'TurnKey Mindtouch Core (Deki) - getting started...',
page_text = '<h2>Getting started</h2> <ul> <li>Log in as <strong>$ADMIN_NAME</strong> and start your Wiki!</li> <li>Refer to the <a class="external" href="http://www.turnkeylinux.org/deki">TurnKey Mindtouch Core (Deki) release notes</a></li> </ul> <p> </p> <pre class="script">&lt;h2&gt;&quot;Welcome to MindTouch&quot;;&lt;/h2&gt; if (user.admin) { wiki.template(&quot;MindTouch/OOBE/Core/Admin_Tabs&quot;); } else { wiki.template(&quot;MindTouch/OOBE/Core/User_Tabs&quot;); } </pre>'
WHERE page_id = '22';
EOF

# install trusted root certificates from mozilla lxr into mono cert store
gzip -d $ETC_DIR/certdata.txt.gz
su dekiwiki -c "mozroots --import --sync --file $ETC_DIR/certdata.txt"
rm $ETC_DIR/certdata.txt

# disable gzip for apache-credit
CONF=$WEB_DIR/includes/DefaultSettings.php
sed -i "s|\$wgUseGzDisplay = \(.*\)|\$wgUseGzDisplay = false;|" $CONF

# stop mysql and apache
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

