#!/bin/bash -e
# regenerate deki mysql password and apikey

. /etc/default/inithooks

PASSWORD=$(mcookie)
APIKEY=$(mcookie)

# update mysql password
CONF=/etc/dekiwiki/LocalSettings.php
MATCH='\$wgDBadminpassword'
sed -i "s|$MATCH\(.*\)|${MATCH} = \"${PASSWORD}\";|" $CONF

CONF=/etc/dekiwiki/mindtouch.deki.startup.xml
MATCH='<db-password hidden=\"true\">'
sed -i "s|$MATCH\(.*\)|${MATCH}${PASSWORD}</db-password>|" $CONF

# update apikey
CONF=/etc/dekiwiki/LocalSettings.php
MATCH='\$wgDekiApiKey'
sed -i "s|$MATCH\(.*\)|${MATCH} = \"${APIKEY}\";|" $CONF

CONF=/etc/dekiwiki/mindtouch.deki.startup.xml
MATCH='<apikey>'
sed -i "s|$MATCH\(.*\)|${MATCH}${APIKEY}</apikey>|" $CONF

CONF=/etc/dekiwiki/mindtouch.host.conf
MATCH='APIKEY='
sed -i "s|$MATCH\(.*\)|${MATCH}\"${APIKEY}\"|" $CONF

APIKEY_QUERY='USE wikidb; UPDATE config SET config_value="$APIKEY" WHERE config_key="security/api-key";'

# update database
$INITHOOKS_PATH/bin/mysqlconf.py --user=wikiuser --pass="$PASSWORD" --query="$APIKEY_QUERY"


